name: Push Stg

on:
  push:
    branches:
      - stg
jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: clasp
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Clasp
        run: |
          npm init -y
          npm install -g @google/clasp

      - name: Set up environment variables
        run: |
          echo "SCRIPT_ID=${{ secrets.STAGING_SCRIPT_ID }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "SCOPE=${{ secrets.SCOPE }}" >> $GITHUB_ENV
          echo "TOKEN_TYPE=${{ secrets.TOKEN_TYPE }}" >> $GITHUB_ENV
          echo "ID_TOKEN=${{ secrets.ID_TOKEN }}" >> $GITHUB_ENV
          echo "EXPIRY_DATE=${{ secrets.EXPIRY_DATE }}" >> $GITHUB_ENV
          echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> $GITHUB_ENV
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> $GITHUB_ENV
          echo "IS_LOCAL_CREDS=${{ secrets.IS_LOCAL_CREDS }}" >> $GITHUB_ENV

      - name: Generate .clasp.json aaa
        run: |
          envsubst < template_clasp.json > .clasp.json
        env:
          SCRIPT_ID: ${{ env.SCRIPT_ID }}

      - name: Generate .clasprc.json
        run: |
          envsubst < template_clasprc.json > .clasprc.json
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          SCOPE: ${{ env.SCOPE }}
          TOKEN_TYPE: ${{ env.TOKEN_TYPE }}
          ID_TOKEN: ${{ env.ID_TOKEN }}
          EXPIRY_DATE: ${{ env.EXPIRY_DATE }}
          REFRESH_TOKEN: ${{ env.REFRESH_TOKEN }}
          CLIENT_ID: ${{ env.CLIENT_ID }}
          CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
          REDIRECT_URI: ${{ env.REDIRECT_URI }}
          IS_LOCAL_CREDS: ${{ env.IS_LOCAL_CREDS }}

      - name: Move .clasprc.json and .clasp.json to home directory
        run: |
          mv .clasprc.json ~/.clasprc.json
          mv .clasp.json ~/.clasp.json

      - name: read Credentials
        run: |
          cat ~/.clasprc.json
          cat ~/.clasp.json

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Push
        run: |
          clasp push -f
